version: '3.3'

services:

  # Cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.44.0
    container_name: ${CADVISOR_CONTAINER_NAME:-cadvisor}
    privileged: true
    restart: always

    devices:
      - /dev/kmsg:/dev/kmsg

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro  # Linux only    

    ports:
      - ${CADVISOR_PORT:-8080}:8080