version: "3.3"

services:

  # Prometheus
  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: ${PROMETHEUS_CONTAINER_NAME:-prometheus}
    restart: always
    user: "$UID:$GID"

    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
  
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"

    volumes:
      - ./prometheus-data:/prometheus # data persistence
      - ./rules.yml:/etc/prometheus/rules.yml
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    networks:
      - epd


networks:
  epd:
    external: true