version: "3.3"

services:

  # Grafana
  grafana:
    image: grafana/grafana-enterprise:9.0.5
    container_name: ${GRAFANA_CONTAINER_NAME:-grafana}
    restart: always
    user: "$UID:$GID"

    ports:
      - ${GF_PORT:-3000}:3000

    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: ${GF_USERS_ALLOW_SIGN_UP:-false}
      GF_AUTH_DISABLE_LOGIN_FORM: ${GF_AUTH_DISABLE_LOGIN_FORM:-false}

    volumes:
      - ./grafana-data:/var/lib/grafana # data persistence
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./config.ini:/etc/grafana/config.ini
      - ./dashboards:/var/lib/grafana/dashboards    

    networks:
      - nginx-proxy-manager


networks:
  nginx-proxy-manager:
    external: true