version: '3.5'

services:

  # pgadmin4
  pgadmin:
    container_name: ${PGDAMIN_CONTAINER_NAME:-pgadmin}
    image: dpage/pgadmin4:6.13
    restart: unless-stopped
    user: "$UID:$GID"

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    volumes:
       - ./pgadmin-data:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-80}:80"

    networks:
      - nginx-proxy-manager


networks:
  nginx-proxy-manager:
    external: true