version: '3.4'

x-common:
  &common
  image: apache/airflow:2.3.0
  user: "${AIRFLOW_UID:-0}:0"
  env_file: 
    - ../.env
  volumes:
    - ./airflow-data/dags:/opt/airflow/dags
    - ./airflow-data/logs:/opt/airflow/logs
    - ./airflow-data/plugins:/opt/airflow/plugins
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    - airflow
    - epd

x-depends-on:
  &depends-on
  depends_on:
    airflow-init:
      condition: service_completed_successfully

services:

  # Airflow Scheduler
  airflow-scheduler:
    <<: *common
    <<: *depends-on
    container_name: airflow-scheduler
    command: scheduler
    restart: on-failure

    ports:
      - "${AIRFLOW_SCHEDULER_PORT}:8793"

  # Airflow Webserver
  airflow-webserver:
    <<: *common
    <<: *depends-on
    container_name: airflow-webserver
    restart: always
    command: webserver

    ports:
      - "${AIRFLOW_WEBSERVER_PORT:-8085}:8080"

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://0.0.0.0:${AIRFLOW_WEBSERVER_PORT}/health"]
      interval: 30s
      timeout: 30s
      retries: 3
  
  # Airflow Initializer
  airflow-init:
    <<: *common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version


networks:
  epd:
    name: epd
    external: true
  airflow:
    name: airflow
    internal: true