version: "3.3"

services:

  # Portainer
  portainer:
    image: portainer/portainer-ce:2.15.1-alpine
    container_name: portainer
    restart: unless-stopped
    command: -H tcp://portainer-agent:${PORTAINER_AGENT_PORT:-9001} --tlsskipverify

    ports:
      - ${PORTAINER_PORT:-9000}:9000

    security_opt:
      - no-new-privileges:true

    volumes:
      - ./portainer-data:/data # data persistence
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - epd


  # Agent
  portainer-agent:
    image: portainer/agent:2.15.1-alpine
    container_name: portainer-agent
    restart: always

    environment:
      AGENT_PORT: ${PORTAINER_AGENT_PORT:-9001}
      # LOG_LEVEL: debug
    
    depends_on:
      - portainer
    
    expose:
      - ${PORTAINER_AGENT_PORT:-9001}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    
    networks:
      - epd


networks:
  epd:
    external: true