version: '3.9'

services:
  minio:
    container_name: minio
    image: minio/minio
    restart: always
    ports:
      - "${MINIO_API_PORT:9000}:9000"         # API port
      - "${MINIO_CONSOLE_PORT:-9001}:9001"    # Console port
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: server --console-address ":9001" /data
    volumes:
      - ./volume/minio:/data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    networks:
      - private
      - nginx

networks:
  private:
    name: private
    internal: true
  nginx:
    name: nginx
    internal: true
