version: "3.3"

services:

  # Node Exporter
  node-exporter:
    image: prom/node-exporter:v1.3.1
    container_name: ${NODE_CONTAINER_NAME:-node}-exporter
    restart: always

    ports:
      - ${NODE_PORT:-9100}:9100

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    
    networks:
      - nginx-proxy-manager


networks:
  nginx-proxy-manager:
    external: true