version: '3.5'

services:

  # Postgres Server
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB:-postgres}", "-U", "${POSTGRES_USER:-postgres}"]
      timeout: 10s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - monitoring
      - epd


  # pgadmin4
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.14
    restart: unless-stopped
    user: "$UID:$GID"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: '${PGADMIN_CONFIG_SERVER_MODE:-False}'  # For servers-side deployment
    volumes:
       - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - epd


networks:
  epd:
    name: epd
    external: true
  monitoring:
    name: monitoring
    internal: true