version: '3.5'

services:

  # Postgres Server
  postgres:
    image: postgres:14-alpine
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
    restart: unless-stopped

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB:-postgres}", "-U", "${POSTGRES_USER:-postgres}"]
      timeout: 10s
      interval: 10s
      retries: 10

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./postgres-data:/var/lib/postgresql/data # data persistence


  # Postgres Exporter
  postgres-exporter:
    image: wrouesnel/postgres_exporter:v0.8.0
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}-exporter
    restart: always

    ports:
      - ${POSTGRES_EXPORTER_PORT:-9187}:9187

    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}?sslmode=${POSTGRES_SSL:-disable}