version: '3.5'

services:

  # Postgres Server
  postgres:
    image: postgres:14-alpine
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB:-postgres}", "-U", "${POSTGRES_USER:-postgres}"]
      timeout: 10s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - epd


  # Postgres Exporter
  postgres-exporter:
    image: wrouesnel/postgres_exporter:v0.8.0
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}-exporter
    restart: always
    ports:
      - ${POSTGRES_EXPORTER_PORT:-9187}:9187
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}?sslmode=${POSTGRES_SSL:-disable}
    networks:
      - epd
  

  # pgadmin4
  pgadmin:
    container_name: ${PGDAMIN_CONTAINER_NAME:-pgadmin}
    image: dpage/pgadmin4:6.14
    restart: unless-stopped
    user: "$UID:$GID"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: '${PGADMIN_CONFIG_SERVER_MODE:-False}'  # For servers-side deployment
    volumes:
       - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-80}:80"
    networks:
      - epd


networks:
  epd:
    external: true