version: '3.5'

services:

  # Grafana
  grafana:
    image: grafana/grafana-enterprise:9.0.5
    container_name: ${GRAFANA_CONTAINER_NAME}
    restart: always
    user: "$UID:$GID"

    ports:
      - ${GF_PORT}:3000

    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: ${GF_USERS_ALLOW_SIGN_UP:-false}
      GF_AUTH_DISABLE_LOGIN_FORM: ${GF_AUTH_DISABLE_LOGIN_FORM:-false}

    volumes:
      - grafana-data:/var/lib/grafana # data persistence
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards    

    labels:
      org.label-schema.group: "monitoring"